tag := "ghcr.io/xssxrt/kind-lain/demo-starlette:latest"
alias b := build
alias r := run
build:
    docker build . -t {{tag}}

run:
    docker run -p 8000:8000 -e MESSAGE="HAHAHHAHAH" {{tag}}

load:
    kind load docker-image {{tag}} --name=prototype

