apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
    - protocol: TCP
      port: {{ include "app.port" . }}
      targetPort: {{ include "app.port" . }}

