name: Demo building image in CI

on:
  push:
    branches: [ main ]
    paths:
      - "clusters/staging/apps/docker-demo/**"
      - "!clusters/staging/apps/docker-demo/readme.md"

jobs:
  push_to_registry:
    name: Build and push image to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # change tag to just be epoch time?
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./clusters/staging/apps/docker-demo
          file: ./clusters/staging/apps/docker-demo/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/demo-nginx:0.0.0
          labels: demo-image

