---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: pihole
  interval: 1m0s
  targetNamespace: pihole
  values:
    persistentVolumeClaim:
      enabled: true
    serviceDns:
      type: LoadBalancer
    serviceWeb:
      type: LoadBalancer

